# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: meaningless_test
  displayName: Some random shell scripts
  jobs:
    - job: meaningless_test_job
      displayName: A meaningless test Job
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'

- stage: build
  displayName: Build
  dependsOn: meaningless_test
  jobs:
    - job: gradlew
      displayName: Gradlew
      steps:
        - task: Gradle@2
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'clean build'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
